if status is-interactive
    abbr --add cat 'bat'
    abbr --add cl 'clear'
    abbr --add config '~/.config/'
    abbr --add dots '~/Projects/dotfiles-ansible'
    abbr --add dls '~/Downloads/'
    abbr --add k 'kubectl'
    abbr --add nmux 'tmux new -s "base"'
    abbr --add projects '~/Projects/'
    abbr --add symlink 'ln -s'
    abbr --add tkill 'tmux kill-session -t'
    abbr --add top 'htop'
    abbr --add vi 'nvim'
    abbr --add vim 'nvim'
end
