---
- name: Install sublime text & plugins in Fedora
  import_tasks: fedora.yml
  when: ansible_distribution == "Fedora"

- name: Install sublime text & plugins in MacOSX
  import_tasks: mac.yml
  when: ansible_distribution == "MacOSX"
