---
- name: Set Nerd Fonts
  set_fact:
    fonts: "['Hack/Regular/complete/Hack Regular Nerd Font Complete.ttf', 'Hack/Bold/complete/Hack Bold Nerd Font Complete.ttf']"

- name: Ensure Nerd Fonts directory exists.
  file:
    group: "{{ ansible_user_gid }}"
    owner: "{{ ansible_user_id }}"
    path: "{{ ansible_env.HOME }}/.local/share/fonts/NerdFonts"
    recurse: true
    state: directory

- name: Download Font
  include_tasks: "nerdfonts.yml"
  loop: "{{ fonts }}"
  loop_control:
    loop_var: font
